# Author: Wyatt Emery
# # Date: Sep 27, 2016
# #
# # COSC 3750, Homework 4
# # 
# # this will compile and generate an executable from wycat.c
# ##############################

CC=gcc
CFLAGS=-Wall -ggdb

wycat: wycat.c
	${CC} ${CFLAGS} wycat.c -o wycat

clean: 
	/bin/rm -f *.o wycat
